<?php

namespace ContainerRPX3K6u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TfWBIefService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TfWBIef' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TfWBIef'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'guideService' => ['privates', 'App\\Service\\GuideService', 'getGuideServiceService', true],
            'subjectRepository' => ['privates', 'App\\Repository\\SubjectRepository', 'getSubjectRepositoryService', true],
        ], [
            'guideService' => 'App\\Service\\GuideService',
            'subjectRepository' => 'App\\Repository\\SubjectRepository',
        ]);
    }
}
