<?php

namespace ContainerRPX3K6u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGuideServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\GuideService' shared autowired service.
     *
     * @return \App\Service\GuideService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/GuideService.php';

        return $container->privates['App\\Service\\GuideService'] = new \App\Service\GuideService();
    }
}
