<?php

namespace ContainerRPX3K6u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLinkCheckerControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Staff\LinkCheckerController' shared autowired service.
     *
     * @return \App\Controller\Staff\LinkCheckerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Staff/LinkCheckerController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/LinkCheckService.php';

        $container->services['App\\Controller\\Staff\\LinkCheckerController'] = $instance = new \App\Controller\Staff\LinkCheckerController(new \App\Service\LinkCheckService(($container->privates['.debug.http_client'] ?? $container->get_Debug_HttpClientService())));

        $instance->setContainer(($container->privates['.service_locator.e5GbwCh'] ?? $container->load('get_ServiceLocator_E5GbwChService'))->withContext('App\\Controller\\Staff\\LinkCheckerController', $container));

        return $instance;
    }
}
