# services to handle doctrine extensions
# import it in config/packages/doctrine_extensions.yaml
#services:
#    # Doctrine Extension listeners to handle behaviors
#    gedmo.listener.sortable:
#        class: Gedmo\Sortable\SortableListener
#        tags:
#            - { name: doctrine.event_subscriber, connection: default }
#        calls:
#            - [ setAnnotationReader, [ "@annotation_reader" ] ]



