<?php 
$I = new AcceptanceTester($scenario);
$I->wantTo('Visit the Admin control page and create a new user');
TestCommons::logMeIn($I);
$I->amOnPage('control/admin/');
$I->see('Users');
$I->click('//*[@id="maincontent"]/div/div[1]/div[1]/div[2]/ul/li[1]/a');
$I->fillField('First Name', 'Test');
$I->fillField('Last Name', 'Testtington');
$I->fillField('Position Title', 'Tester');
$I->fillField('Position #', '5');
$I->fillField('Job Classification', 'Testing');
$I->fillField('#tel', '555-5555');
$I->fillField('//*[@id="email"]', 'test@example.com');
$I->fillField('#street_address', 'Test Avenue');
$I->fillField('City', 'Testville');
$I->fillField('State', 'Testasota');
$I->fillField('#zip', '90210');
$I->fillField('#home_phone', '555-5555');
$I->fillField('#cell_phone', '555-5555');
$I->fillField('#emergency_contact_name', 'Tester Jr.');
$I->fillField('#emergency_contact_relation', 'Co-Tester');
$I->fillField('//*[@id="emergency_contact_phone"]', '555-5555');
$I->fillField('//*[@id="new_record"]/div[3]/div[2]/div[2]/input', '55445$%$5grggrg5Ff');
$I->click('Save Record Now');
$I->seeElement('#feedback');
