########################################
# Full List of Constraints: https://symfony.com/doc/current/reference/constraints.html
# Follow the YAML examples for applying a specific constraint.
# 
# NOTES
# Omitting the "groups" field will keep the constraint apart of the default group.
# How to apply validation groups: https://symfony.com/doc/current/form/validation_groups.html
#
# FORMAT
# App\Entity\[EntityName]:
#   constraints:
#     - [Constraint]:
#          fields: [ [EntityPropertyName], ... ]
#          message: "[ErrorMessage]"
#          groups: [ [GroupName] ]
#   properties:
#     [EntityPropertyName]:
#       - [Constraint]:
#            message: "[ErrorMessage]"
#            groups: [ [GroupName] ]
#
########################################

App\Entity\Subject:
    properties:
        shortform:
            - Regex:
                # pattern does not allow capital letters, spaces, special characters other than dashes,
                # the words api or control as the sole shortform,
                # but allows variants of the words such as api-info, controller, etc.
                pattern: '/^(?!\b(api|control)\b(?![\w-]))[A-Za-z0-9-]+$/'
                message: 'subjects.constraints.shortform.regex'

    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [subject]
            message: 'subject.constraints.subject_field.unique_entity'
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [shortform]
            message: 'subject.constraints.shortform.unique_entity'