<?php

namespace ContainerMS5FBSd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGuideControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Patron\GuideController' shared autowired service.
     *
     * @return \App\Controller\Patron\GuideController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Patron/GuideController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/PlusletService.php';

        $container->services['App\\Controller\\Patron\\GuideController'] = $instance = new \App\Controller\Patron\GuideController(($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService()), new \App\Service\PlusletService());

        $instance->setContainer(($container->privates['.service_locator.nWfG7Gw'] ?? $container->load('get_ServiceLocator_NWfG7GwService'))->withContext('App\\Controller\\Patron\\GuideController', $container));

        return $instance;
    }
}
