<?php

namespace ContainerMS5FBSd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Patron\IndexController' shared autowired service.
     *
     * @return \App\Controller\Patron\IndexController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Patron/IndexController.php';

        $container->services['App\\Controller\\Patron\\IndexController'] = $instance = new \App\Controller\Patron\IndexController(($container->privates['App\\Service\\DatabaseService'] ?? $container->getDatabaseServiceService()));

        $instance->setContainer(($container->privates['.service_locator.nWfG7Gw'] ?? $container->load('get_ServiceLocator_NWfG7GwService'))->withContext('App\\Controller\\Patron\\IndexController', $container));

        return $instance;
    }
}
