<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRPX3K6u\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRPX3K6u/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRPX3K6u.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRPX3K6u\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRPX3K6u\App_KernelDevDebugContainer([
    'container.build_hash' => 'RPX3K6u',
    'container.build_id' => 'd9339349',
    'container.build_time' => 1624563543,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRPX3K6u');
