<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'guidebyParam' => [[], ['_controller' => 'App\\Controller\\Patron\\GuideController::showPublicGuideByQueryParams'], [], [['text', '/subjects/guide.php']], [], []],
    'guidesAutocomplete' => [[], ['_controller' => 'App\\Controller\\Patron\\GuideController::autocompleteGuides'], [], [['text', '/api/autocomplete/guides.json']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\Patron\\IndexController::index'], [], [['text', '/']], [], []],
    'index.php' => [[], ['_controller' => 'App\\Controller\\Patron\\IndexController::index'], [], [['text', '/index.php']], [], []],
    'subjects' => [[], ['_controller' => 'App\\Controller\\Patron\\IndexController::index'], [], [['text', '/subjects/']], [], []],
    'subjects/index.php' => [[], ['_controller' => 'App\\Controller\\Patron\\IndexController::index'], [], [['text', '/subjects/index.php']], [], []],
    'guidebyShortname' => [['shortform'], ['_controller' => 'App\\Controller\\Patron\\GuideController::showPublicGuide'], ['shortform' => '(?!.*?\\.php).*'], [['variable', '/', '(?!.*?\\.php).*', 'shortform', true], ['text', '/subjects']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\AuthController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\AuthController::logout'], [], [['text', '/logout']], [], []],
    'databasesAutocomplete' => [[], ['_controller' => 'App\\Controller\\Patron\\DatabaseListController::autocompleteDatabases'], [], [['text', '/api/autocomplete/databases.json']], [], []],
    'public_database_list' => [[], ['_controller' => 'App\\Controller\\Patron\\DatabaseListController::index'], [], [['text', '/subjects/databases.php']], [], []],
    'staff_link_checker' => [[], ['_controller' => 'App\\Controller\\Staff\\LinkCheckerController::index'], [], [['text', '/control/guides/link_checker.php']], [], []],
    'link_checker_api' => [[], ['_controller' => 'App\\Controller\\Staff\\LinkCheckerController::links'], [], [['text', '/control/guides/check_links.json']], [], []],
];
